#!/bin/bash

set -x;
if [ $# -eq 0 ]
  then
    echo "No arguments"
        exit 0
fi

SandboxID=`printf "%02d" $1`


if [ -e "/root/sandbox/status/$SandboxID" ];then
	Template=`awk '/^template/{print $NF}' /root/sandbox/status/${SandboxID}`
        prlctl stop Template_${Template}_jumper

        VE_LIST=`awk '/^ve_list/{print $NF}' /root/sandbox/status/${SandboxID}`
        for VE_ID in `echo $VE_LIST | sed 's/;/ /g'`; do
                prlctl stop Template_${Template}_ve${VE_ID}
        done

	#delete external ip address from jumper
	IP=`awk '/^ip/{print $NF}' /root/sandbox/status/${SandboxID}`
	prlctl set Template_${Template}_jumper --device-set net0 --ipdel $IP	
	
	rm /root/sandbox/status/$SandboxID
else
        echo "cannot find sandbox status file /root/sandbox/status/$SandboxID"
        fi

set +x;
