#!/bin/bash

set -x;
if [ $# -eq 0 ]; then
	echo "No arguments"
	exit 0
fi

SandboxID=`printf "%02d" $1`

/root/sandbox/sandbox-stop $1	
	
if [ -e "/root/sandbox/status/$SandboxID" ];then

	sed -i 's/^\(status\s*=\s*\).*$/\1deleting/' /root/sandbox/status/$SandboxID
	
	prlctl delete jumper-${SandboxID}
	
	VE_LIST=`awk '/^ve_list/{print $NF}' /root/sandbox/status/${SandboxID}`
	for VE_ID in `echo $VE_LIST | sed 's/;/ /g'`; do
		prlctl delete ve-${SandboxID}-${VE_ID}
	done
	
	rm /root/sandbox/status/$SandboxID
else
	echo "cannot find sandbox status file /root/sandbox/status/$SandboxID"
fi
	
set +x;