#!/bin/bash

set -x;

if [ $# -eq 0 ]; then
        echo "No arguments"
    exit 0
fi

SandboxID=`printf "%02d" $1`

CONFIG=$2

if [ -e "/root/sandbox/status/$SandboxID" ];then
        echo "sandbox status file /root/sandbox/status/$SandboxID exists"
    exit 0
else
        echo "status = NetworkSetting" >> /root/sandbox/status/$SandboxID

        TemplateName=`awk '/^template/{print $NF}' $CONFIG`
        echo "template = $TemplateName" >> /root/sandbox/status/$SandboxID

        Domain=`awk '/^domain/{print $NF}' $CONFIG`
        echo "domain = $Domain" >> /root/sandbox/status/$SandboxID

        UserPassword=`date|md5sum |awk '{print substr($0,0,10)}'`
        echo "password = $UserPassword" >> /root/sandbox/status/$SandboxID

        Sandbox_IP=`awk '/^sandbox-'$SandboxID'-VLAN/{print $NF}' /root/sandbox/config/ip.cfg`
        echo "ip = $Sandbox_IP" >> /root/sandbox/status/$SandboxID
        prlctl set Template_${TemplateName}_jumper --device-set net0 --ipadd ${Sandbox_IP}/24
        prlctl set Template_${TemplateName}_jumper --device-set net1 --network sandbox-${SandboxID}-VLAN --ipadd 10.111.22.1

        IPLayout=`awk '/^ip-layout/{print $NF}' $CONFIG`
        IFS=';' read -ra VE_LIST_WITH_IP <<< "$IPLayout"

        for i in "${VE_LIST_WITH_IP[@]}"; do
                IFS=':' read -ra VE <<< "$i"
                prlctl set Template_${TemplateName}_ve${VE[0]} --device-set net0 --network sandbox-${SandboxID}-VLAN --ipadd 10.111.22.${VE[1]}

                VE_LIST+=${VE[0]}
                VE_LIST+=";"
        done

        echo "ve_list = $VE_LIST" >> /root/sandbox/status/$SandboxID

        sed -i 's/^\(status\s*=\s*\).*$/\1starting/' /root/sandbox/status/$SandboxID

        prlctl start Template_${TemplateName}_jumper

        VE_LIST=`awk '/^ve_list/{print $NF}' /root/sandbox/status/${SandboxID}`
        for VE_ID in `echo $VE_LIST | sed 's/;/ /g'`; do
                prlctl start Template_${TemplateName}_ve${VE_ID}
        done

        sed -i 's/^\(status\s*=\s*\).*$/\1template_started/' /root/sandbox/status/$SandboxID


	sandbox-template-init $1
fi

set +x;
