#!/bin/bash

set -x;

if [ $# -eq 0 ]; then
        echo "No arguments"
    exit 0
fi

SourceConfig=$1

DestConfig=$2

SourceTemplateName=`awk '/^template/{print $NF}' $SourceConfig`
DestTemplateName=`awk '/^template/{print $NF}' $DestConfig`

prlctl clone Template_${SourceTemplateName}_jumper --name Template_${DestTemplateName}_jumper


IPLayout=`awk '/^ip-layout/{print $NF}' $DestConfig`
IFS=';' read -ra VE_LIST_WITH_IP <<< "$IPLayout"

for i in "${VE_LIST_WITH_IP[@]}"; do
	IFS=':' read -ra VE <<< "$i"
	prlctl clone Template_${SourceTemplateName}_ve${VE[0]} --name Template_${DestTemplateName}_ve${VE[0]}
done

set +x;
