#!/bin/bash

set -x;
if [ $# -eq 0 ]; then
    echo "No arguments"
    exit 0
fi

function pau_restart() {
        prlctl exec Template_${TemplateName}_ve14 "systemctl stop pa-agent && systemctl stop pau"
        sleep 30
        prlctl exec Template_${TemplateName}_ve14 "pkill -9 java"
        prlctl exec Template_${TemplateName}_ve14 "pkill -9 pa-watchdog"
        prlctl exec Template_${TemplateName}_ve14 "pkill -9 pa-agent"
        prlctl exec Template_${TemplateName}_ve14 "systemctl start pau"

        prlctl exec Template_${TemplateName}_ve14 "systemctl status pau"
        sleep 120
        prlctl exec Template_${TemplateName}_ve14 "systemctl start pa-agent"
        if [ $? -ne 0 ]; then
                sleep 60
                prlctl exec Template_${TemplateName}_ve14 "systemctl start pa-agent"
                if [ $? -ne 0 ]; then
                        exit 0
                fi
        fi
}

SandboxID=`printf "%02d" $1`

if [ -e "/root/sandbox/status/$SandboxID" ];then

	sed -i 's/^\(status\s*=\s*\).*$/\1template_init/' /root/sandbox/status/$SandboxID
	
	TemplateName=`awk '/^template/{print $NF}' /root/sandbox/status/${SandboxID}`


	for ((n=0;n<10;n++))
	do
        	prlctl exec Template_${TemplateName}_jumper echo "VM is started"
		if [ $# -eq 0 ]; then
                	break
        	fi
	done


        prlctl exec Template_${TemplateName}_jumper "systemctl stop ntpdate"
        prlctl exec Template_${TemplateName}_jumper "ntpdate -s 0.de.pool.ntp.org"
        prlctl exec Template_${TemplateName}_jumper "systemctl start ntpdate"

        UserPassword=`awk '/^password/{print $NF}' /root/sandbox/status/${SandboxID}`
        prlctl set Template_${TemplateName}_jumper --userpasswd lab:$UserPassword

	prlctl exec Template_${TemplateName}_jumper "systemctl start squid"

	prlctl exec Template_${TemplateName}_ve14 "echo ok"
	prlctl exec Template_${TemplateName}_ve14 "systemctl stop ntpdate"
	
        prlctl exec Template_${TemplateName}_ve14 "ntpdate -s 0.de.pool.ntp.org"
        prlctl exec Template_${TemplateName}_ve14 "systemctl start ntpdate"
        prlctl exec Template_${TemplateName}_ve14 "ip r a 10.96.0.0/12 via 10.111.22.23 dev eth0"
	prlctl exec Template_${TemplateName}_ve14 "if grep -P '^search' /etc/resolv.conf; then sed -i 's/^search.*/& default.svc.cluster.local/' /etc/resolv.conf; else sed -i '1s/^/search default.svc.cluster.local\n/' /etc/resolv.conf; fi"


	pau_restart

        prlctl exec Template_${TemplateName}_ve23 echo ok
        prlctl exec Template_${TemplateName}_ve23 "systemctl stop ntpdate"
        prlctl exec Template_${TemplateName}_ve23 "ntpdate -s 0.de.pool.ntp.org"
        prlctl exec Template_${TemplateName}_ve23 "systemctl start ntpdate"

        prlctl exec Template_${TemplateName}_ve33 echo ok
        prlctl exec Template_${TemplateName}_ve33 "systemctl stop ntpdate"
        prlctl exec Template_${TemplateName}_ve33 "ntpdate -s 0.de.pool.ntp.org"
        prlctl exec Template_${TemplateName}_ve33 "systemctl start ntpdate"
        prlctl set Template_${TemplateName}_ve33 --ipfilter no --macfilter no --preventpromisc no
        prlctl exec Template_${TemplateName}_ve33 'brctl addif br0 eth0'
        prlctl exec Template_${TemplateName}_ve33 'ip r d 10.111.22.0/24 dev eth0'
        prlctl exec Template_${TemplateName}_ve33 'ip r d 10.111.22.1 dev eth0'

        prlctl exec Template_${TemplateName}_ve34 echo ok
        prlctl exec Template_${TemplateName}_ve34 "systemctl stop ntpdate"
        prlctl exec Template_${TemplateName}_ve34 "ntpdate -s 0.de.pool.ntp.org"
        prlctl exec Template_${TemplateName}_ve34 "systemctl start ntpdate"
        prlctl set Template_${TemplateName}_ve34 --ipfilter no --macfilter no --preventpromisc no
        prlctl exec Template_${TemplateName}_ve34 'brctl addif br0 eth0'
        prlctl exec Template_${TemplateName}_ve34 'ip r d 10.111.22.0/24 dev eth0'
        prlctl exec Template_${TemplateName}_ve34 'ip r d 10.111.22.1 dev eth0'

        prlctl exec Template_${TemplateName}_ve35 echo ok
        prlctl exec Template_${TemplateName}_ve35 "systemctl stop ntpdate"
        prlctl exec Template_${TemplateName}_ve35 "ntpdate -s 0.de.pool.ntp.org"
        prlctl exec Template_${TemplateName}_ve35 "systemctl start ntpdate"
        prlctl set Template_${TemplateName}_ve35 --ipfilter no --macfilter no --preventpromisc no
        prlctl exec Template_${TemplateName}_ve35 'brctl addif br0 eth0'
        prlctl exec Template_${TemplateName}_ve35 'ip r d 10.111.22.0/24 dev eth0'
        prlctl exec Template_${TemplateName}_ve35 'ip r d 10.111.22.1 dev eth0'


	sed -i 's/^\(status\s*=\s*\).*$/\1template_ok/' /root/sandbox/status/$SandboxID
	
else
	echo "cannot find sandbox status file /root/sandbox/status/$SandboxID"	
	fi

set +x;


